from __future__ import annotations

from datetime import date
from typing import Protocol

from fitness_predictor.models import LiftLog, NutritionLog, UserProfile


class StorageBackend(Protocol):
    def save_profile(self, profile: UserProfile) -> None: ...
    def load_profile(self) -> UserProfile | None: ...
    def save_nutrition_log(self, log: NutritionLog) -> None: ...
    def load_nutrition_logs(self, start_date: date | None = None, end_date: date | None = None) -> list[NutritionLog]: ...
    def update_nutrition_log(self, log_date: date, updated: NutritionLog) -> bool: ...
    def delete_nutrition_log(self, log_date: date) -> bool: ...
    def save_lift_log(self, log: LiftLog) -> None: ...
    def load_lift_logs(self, exercise: str | None = None, start_date: date | None = None, end_date: date | None = None) -> list[LiftLog]: ...
